Lamazon/Lamazon.WebApp/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lamazon.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Lamazon.WebModels.ViewModels;
using Lamazon.WebModels.Enums;
using Newtonsoft.Json;

namespace Lamazon.WebApp.Controllers
{
    [Authorize]
    public class InvoicesController : Controller
    {
        private readonly IInvoiceService _invoiceService;
        private readonly IOrderService _orderService;

        public InvoicesController(IInvoiceService invoiceService, IOrderService orderService)
        {
            _invoiceService = invoiceService;
            _orderService = orderService;
        }

        [Authorize(Roles = "customer")]
        [HttpPost]
        public IActionResult Pay(InvoiceViewModel invoice)
        {
            _invoiceService.CreateInvoice(
                invoice
            );

            _orderService.ChangeStatus(invoice.OrderId, StatusTypeViewModel.Paid);

            return RedirectToAction("ListUserOrders", "Orders");
        }

        // Used for vanilla JavaScript ajax
        [Authorize(Roles = "customer, admin")]
        public string ShowInvoice(int orderId)
        {
            InvoiceViewModel invoice = _invoiceService.GetInvoice(orderId);

            var invoiceJs = new
            {
                invoice.Id,
                PaymentMethod = Enum.GetName(typeof(PaymentTypeViewModel), invoice.PaymentMethod),
                invoice.Address,
                invoice.Price,
                invoice.OrderId
            };

            return JsonConvert.SerializeObject(invoiceJs);
        }
    }
}

Lamazon/Lamazon.WebApp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lamazon.Services.Interfaces;
using Lamazon.WebModels.Enums;
using Lamazon.WebModels.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lamazon.WebApp.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;

        public OrdersController(IOrderService orderService, IUserService userService)
        {
            _orderService = orderService;
            _userService = userService;
        }

        [Authorize(Roles = "customer, supplier, admin")]
        public IActionResult OrderDetails(int orderId)
        {
            return View(_orderService.GetOrderById(orderId));
        }

        [Authorize(Roles = "customer")]
        public IActionResult ListUserOrders()
        {
            UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);

            ViewBag.UserOption = UserOptions.Customer;
            ViewBag.WebAppBaseUrl = $"{Request.Scheme}://{Request.Host.Value}";
            return View("Index", _orderService.GetUserOrders(user.Id));
        }

        [Authorize(Roles = "customer")]
        public IActionResult FinishOrder(int orderId)
        {
            _orderService.ChangeStatus(orderId, StatusTypeViewModel.Processing);

            return RedirectToAction(nameof(ListUserOrders));
        }

        [Authorize(Roles = "customer")]
        public IActionResult CancelOrder(int orderId)
        {
            _orderService.ChangeStatus(orderId, StatusTypeViewModel.Canceled);

            return RedirectToAction(nameof(ListUserOrders));
        }

        [Authorize(Roles = "supplier, admin")]
        public IActionResult ListAllOrders()
        {
            ViewBag.UserOption = UserOptions.Supplier;
            ViewBag.WebAppBaseUrl = $"{Request.Scheme}://{Request.Host.Value}";
            return View("Index", _orderService.GetAllOrders());
        }

        [Authorize(Roles = "supplier, admin")]
        public IActionResult ConfirmOrder(int orderId)
        {
            _orderService.ChangeStatus(orderId, StatusTypeViewModel.Confirmed);

            return RedirectToAction(nameof(ListAllOrders));
        }

        [Authorize(Roles = "supplier, admin")]
        public IActionResult DeclineOrder(int orderId)
        {
            _orderService.ChangeStatus(orderId, StatusTypeViewModel.Declined);

            return RedirectToAction(nameof(ListAllOrders));
        }

        [Authorize(Roles = "supplier, admin")]
        public IActionResult MarkAsDelivered(int orderId)
        {
            _orderService.ChangeStatus(orderId, StatusTypeViewModel.Delivered);

            return RedirectToAction(nameof(ListAllOrders));
        }
    }
}

Lamazon/Lamazon.WebApp/Views/Orders/Index.cshtml
@model IEnumerable<OrderViewModel>

@{
    ViewData["Title"] = "Orders";
    //bool IsSupplier = User.IsInRole("supplier");

}

<h2>Orders</h2>

<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Status</th>
            <th>Price</th>
            <th>User</th>
            <th>Product</th>
        </tr>
    </thead>
    <tbody>
        @foreach (OrderViewModel o in Model)
        {
        <tr>
            <td>@o.Id</td>
            <td>@o.Status</td>
            <td>@o.Price$</td>
            <td>@o.User.FullName</td>
            <td>
                <a class="btn btn-default" asp-controller="Orders" asp-action="OrderDetails" asp-route-orderId="@o.Id">Order Details</a>
            </td>

            <td>
                @if (ViewBag.UserOption == UserOptions.Customer)
                {
                    @if (o.Status == StatusTypeViewModel.Init)
                    {

                        <a class="btn btn-primary" asp-controller="Orders" asp-action="FinishOrder" asp-route-orderId="@o.Id">Finish</a>
                        <a class="btn btn-primary" asp-controller="Orders" asp-action="CancelOrder" asp-route-orderId="@o.Id">Cancel</a>
                    }
                    @if (o.Status == StatusTypeViewModel.Confirmed)
                    {
                        ViewData["OrderId"] = o.Id;
                        string paymentPopupId = $"#paymentPopup{o.Id}";

                            <button class="btn btn-danger" data-toggle="modal" data-target="@paymentPopupId">Pay</button>
                            <partial name="PaymentPopup" model="new InvoiceViewModel()" view-data="ViewData" />
                    }
                    @if (o.Status == StatusTypeViewModel.Paid || o.Status == StatusTypeViewModel.Delivered)
                    {
                        ViewData["OrderId"] = o.Id;
                        string invoicePopupId = $"#invoicePopup{o.Id}";

                            <button onclick="getInvoiceData(@o.Id)" class="btn btn-danger" data-toggle="modal" data-target="@invoicePopupId">Show Invoice</button>
                            <partial name="InvoicePopup" view-data="ViewData" />
                    }
                }
                else if (ViewBag.UserOption == UserOptions.Supplier || ViewBag.UserOption == UserOptions.Admin)
                {
                    @if (o.Status == StatusTypeViewModel.Processing)
                    {
                            <a class="btn btn-primary" asp-controller="Orders" asp-action="ConfirmOrder" asp-route-orderId="@o.Id">Approve</a>
                            <a class="btn btn-primary" asp-controller="Orders" asp-action="DeclineOrder" asp-route-orderId="@o.Id">Decline</a>
                    }
                    @if (o.Status == StatusTypeViewModel.Paid)
                    {
                            <a class="btn btn-primary" asp-controller="Orders" asp-action="MarkAsDelivered" asp-route-orderId="@o.Id">Mark as delivered</a>
                    }
                }
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    function getInvoiceData(orderId) {
        console.log("live!")
        fetch(`@ViewBag.WebAppBaseUrl/Invoices/ShowInvoice?orderId=${orderId}`)
            .then(res => res.json())
            .then(data => {

                console.log(data)

                let paymentMethod = document.getElementById(`IPPaymentMethod${orderId}`)
                let address = document.getElementById(`IPAddress${orderId}`)
                let price = document.getElementById(`IPPrice${orderId}`)

                paymentMethod.value = data.PaymentMethod
                address.value = data.Address
                price.value = data.Price + "$"
            })
    }
</script>

Lamazon/Lamazon.WebApp/Views/Orders/InvoicePopup.cshtml
@{
    string popupId = $"invoicePopup{ViewData["OrderId"]}";
    string paymentMethodId = $"IPPaymentMethod{ViewData["OrderId"]}";
    string addressId = $"IPAddress{ViewData["OrderId"]}";
    string priceId = $"IPPrice{ViewData["OrderId"]}";
}

<div id="@popupId" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Invoice</h3>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="">Payment Method</label>
                        <input class="form-control" id="@paymentMethodId" />
                    </div>
                    <div class="form-group">
                        <label for="">Address</label>
                        <input class="form-control" id="@addressId" />
                    </div>
                    <div class="form-group">
                        <label for="">Price</label>
                        <input class="form-control" id="@priceId" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Lamazon/Lamazon.WebApp/Views/Orders/OrderDetails.cshtml
@model OrderViewModel

@{
    ViewData["Title"] = "Order Details";
}

<h2>Order Details</h2>

<div class="container">
    <div class="col-sm-4">
        <ul class="list-group">
            <li class="list-group-item active">User:</li>
            <li class="list-group-item">@Model.User.FullName</li>
            <li class="list-group-item active">Status:</li>
            <li class="list-group-item">@Model.Status</li>
            <li class="list-group-item active">Price:</li>
            <li class="list-group-item">@Model.Price$</li>
            <li class="list-group-item active">Products:</li>
            <li class="list-group-item">
                <ul class="list-group">
                    @foreach (ProductViewModel p in Model.Products)
                    {
                        <li class="list-group-item alert-info">@p.Name</li>
                        @*<li class="list-group-item">@p.Category</li>*@
                        <li class="list-group-item">@p.Price$</li>
                    }
                </ul>
            </li>
        </ul>
    </div>
</div>

Lamazon/Lamazon.WebApp/Views/Orders/PaymentPopup.cshtml
@model InvoiceViewModel

@{ 
    string popupId = $"paymentPopup{ViewData["OrderId"]}";
}

<div id="@popupId" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-controller="Invoices" asp-action="Pay" method="post">
                <div class="modal-header">
                    <h3 class="modal-title">Payment method</h3>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="">Payment Method</label>
                        <input asp-for="PaymentMethod" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="">Address</label>
                        <input asp-for="Address" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="">Order ID:</label>
                        <input readonly asp-for="OrderId" value="@ViewData["OrderId"]" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Pay Now</button>
                </div>
            </form>
        </div>
    </div>
</div>